Autopipelining
ShogunPanda/ioredis pull request #1
Opened 2020-09-25 11:35 UTC by ShogunPanda

2020-09-25 11:42 UTC, mcollina commented on lib/autoPipelining.ts
> +    });
Can we check if we are ready and avoid the promise-wrapping?

2020-09-25 11:42 UTC, mcollina commented on lib/autoPipelining.ts
> +    process.nextTick(executeAutoPipeline, client, slotKey);
This needs a comment

2020-09-25 11:42 UTC, mcollina commented on lib/pipeline.ts
> +  const now = Date.now();
Why is this created?

2020-09-25 11:56 UTC, ShogunPanda commented on lib/autoPipelining.ts
> +    });
About checking if ready, it is already done: when ready, the slots on line 73 will not be empty.
I don't think promise wrapping is avoidable, unfortunately. The return value of this function is directly returned in `lib/commander.js` as the return value of the command. ioredis API supports both promise and callback so we must keep it.

2020-09-25 12:01 UTC, ShogunPanda commented on lib/pipeline.ts
> +  const now = Date.now();
This is to address https://github.com/luin/ioredis/issues/536.
To allow custom commands in the cluster pipeline we need to make sure the script is loaded. This loading is done outside of the auto pipeline.
Now, doing this on each execution would probably have severely impacted performance, so I added a cache which throttles the loading of script to at most once per minute.

2020-09-25 12:02 UTC, ShogunPanda commented on lib/autoPipelining.ts
> +    process.nextTick(executeAutoPipeline, client, slotKey);
Done

2020-09-25 13:08 UTC, mcollina commented on lib/autoPipelining.ts
> +    });
ok!

2020-09-25 13:19 UTC, mcollina requested changes
Can you also add the PR text?

2020-09-25 13:19 UTC, mcollina commented on lib/pipeline.ts
> +    ).then(execPipeline);
I would not use p-map here as it is not really protecting for anything.

2020-09-25 13:19 UTC, mcollina commented on lib/pipeline.ts
> +  const now = Date.now();
This is created _for every pipeline_, even the ones without Lua scripts. Calling `Date.now()` is expensive so we should try to avoid it. Why would you cache scripts for _only_ 60 seconds_. I would prefer that the `this.redis.addedScriptHashes` is cleared every minute or so.

2020-09-25 13:19 UTC, mcollina commented on lib/pipeline.ts
> +        this.redis.addedScriptHashes[script.sha] - now < this.redis.options.maxScriptsCachingTime
`maxScriptsCachingTime` seems to only be used when we are not in cluster mode, but https://github.com/luin/ioredis/issues/536 is specifically about cluster mode.

2020-09-25 13:24 UTC, mcollina commented on API.md
> +| [options.enableAutoPipelining] | <code>boolean</code> | <code>false</code> | When enabled, all commands issued during an event loop iteration are automatically wrapped in a pipeline and sent to the
```suggestion
| [options.enableAutoPipelining] | <code>boolean</code> | <code>false</code> | When enabled, all commands issued during an event loop iteration are automatically wrapped in a pipeline and sent to the server at the same time. This can improve performance by 30-50%. |
```

2020-09-28 13:29 UTC, ShogunPanda commented on lib/pipeline.ts
> +        this.redis.addedScriptHashes[script.sha] - now < this.redis.options.maxScriptsCachingTime
Good point. The if on line 307 is not needed. Removing.

2020-09-28 13:43 UTC, ShogunPanda commented on lib/pipeline.ts
> +    ).then(execPipeline);
Why not? Think about pipelining - If an automatic pipeline of 1000 commands has 500 different custom commands, it can potentially fire 500 concurrent `SCRIPT LOAD` requests using `Promise.all` (since `_this.redis` is outside of the pipeline). 

As we know it's not a good idea, I limited concurrency with `p-map`.

2020-09-28 13:55 UTC, ShogunPanda commented on lib/pipeline.ts
> +  const now = Date.now();
Fixed now. What do you think?

2020-09-30 10:06 UTC, mcollina commented on lib/autoPipelining.ts
> +    setImmediate(executeAutoPipeline, client, slotKey);
```suggestion
    // Deferring with setImmediate so we have a chance to capture multiple
    // commands that can be scheduled by I/O events already in the
    // event loop queue
    setImmediate(executeAutoPipeline, client, slotKey);
```

2020-09-30 11:13 UTC, ShogunPanda commented on benchmarks/single_node.ts
> -import Redis from "../lib/redis";
Actually the test was unmaintaned, as stated here - https://github.com/luin/ioredis/issues/1156.
I wouldn't worry for now. We can revisit later if they ask us.

2020-10-01 12:20 UTC, ShogunPanda commented
Superseded by https://github.com/luin/ioredis/pull/1201 - Closing.

2020-10-01 12:20 UTC, closed without merging